### PR TITLE
Hw 1

### PR DESCRIPTION
**Pull request by maxkvant**

### CODE REVIEW

**Review by Rauf-Kurbanov — CHANGES_REQUESTED** [review]
Please replace `.wav` files with download by `wget` it is a bad practice to keep large files in the repo

**Comment by maxkvant** [comment]
Folder bg_noise in this repo contains ~2MB

**Comment by maxkvant** [comment]
I've replaced it, anyway.
Now whoever wants to use the default running line should download bg_noise before.

**Review by Rauf-Kurbanov — APPROVED** [review]
Now looks great

**Pull request merged**
